# Fungsi

- Sudah pernah kita gunakan
- Contoh: type()
- Kumpulan code yang digunakan kembali
- Menyelesaikan tugas yang spesifik
- Panggil fungsi yang sudah ada daripada harus membuat sendiri dari awal

In [2]:
keluarga = [1.73, 1.68, 1.71, 1.89]

In [3]:
keluarga

[1.73, 1.68, 1.71, 1.89]

In [4]:
max(keluarga)

1.89

In [6]:
paling_tinggi = max(keluarga)

In [7]:
paling_tinggi

1.89

In [8]:
len(keluarga)

4

In [9]:
round(1.68, 1)

1.7

In [10]:
round(1.68)

2

In [11]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



## Fungsinya apa aja?

- Kalau fungsi standar biasanya sudah disediakan misal max, min, sum, dll
- Internet adalah teman anda

## Fungsi Built-in

- Maksimum dari list: max()
- Panjang dari list: len()
- Mendapatkan index dari list: ?
- Me reverse list: ?

## Method

In [27]:
adik = 'balqis' # Object tipe: str contoh method: capitalize(), replace()

tinggi = 1.73 # Object tipe: float contoh method: bit_length(), conjugate()

keluarga = [1.73, 1.68, 1.71, 1.89] # Object tipe: list contoh method: index(), count()


## List Method

In [33]:
keluarga = ['kakak', 1.73, 'adik', 1.68, 'ibu', 1.71, 'ayah', 1.89]

In [15]:
keluarga.index('adik')

2

In [16]:
keluarga.count(1.73)

1

## Str Method

In [28]:
adik

'balqis'

In [29]:
adik.capitalize()

'Balqis'

In [30]:
adik.replace('i', 'y')

'balqys'

- Semua dalam Python merupakan Object
- Setiap Object memiliki method yang sesuai dengan objectnya

In [25]:
# keluarga.replace('ibu', 'mama')

In [31]:
adik.index('a')

1

In [34]:
keluarga.index('ibu')

4

In [35]:
keluarga.append('saya')

In [36]:
keluarga

['kakak', 1.73, 'adik', 1.68, 'ibu', 1.71, 'ayah', 1.89, 'saya']

In [37]:
keluarga.append(1.76)

In [38]:
keluarga

['kakak', 1.73, 'adik', 1.68, 'ibu', 1.71, 'ayah', 1.89, 'saya', 1.76]

## Ingat

### Fungsi

In [41]:
type(keluarga)

list

### Method: merupakan fungsi pada object

In [42]:
keluarga.index('ibu')

4

## Package

- Fungsi dan Method sangat <i>powerfuul</i>
- Semua kode dalam satu Python?

Apakah Package / Paket itu?
- Sebuah directory Script Python
- Setiap Script = Modul
- Mempunyai fungsi, method, tipe yang spesifik
- Ribuan paket tersedia tergantung keperluan
- Contoh: NumPy, Matplotlib, Scikit-learn

## Install Package

- Jika kamu menggunakan anaconda maka semua paket untuk keperluan Data Science sudah tersedia
- Jika kamu ingin mencoba install Python dari awal maka ada dua kemungkinan
- 1. pip belum tersedia, 2. pip sudah tersedia
- Jika belum tersedia download di http://pip.readthedocs.org/en/stable/installing/
- Download get-pip.py
- Buka Terminal / CMD
- python3 get-pip.py (Linux/MacOS) python get-pip.py (Windows)
- Untuk menginstall NumPy
- pip3 install numpy (Linux/MacOS) pip install numpy (Windows)


## Import Package

In [46]:
import numpy

In [45]:
# array([1, 2, 3]) --> error

In [48]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [49]:
import numpy as np 

In [50]:
np.array([1, 2, 3])

array([1, 2, 3])

In [51]:
from numpy import array

In [52]:
array([1, 2, 3])

array([1, 2, 3])

### From numpy import array

In [57]:
from numpy import array

keluarga = ['kakak', 1.73, 'adik', 1.68, 'ibu', 1.71, 'ayah', 1.89]

keluarga_tambahan = keluarga + ['saya', 1.76]

print(str(len(keluarga_tambahan)) + ' elemen pada keluarga_tambahan')

np_keluarga = array(keluarga_tambahan) # Menggunakan NumPy, tapi tidak begitu jelas

print(np_keluarga)

10 elemen pada keluarga_tambahan
['kakak' '1.73' 'adik' '1.68' 'ibu' '1.71' 'ayah' '1.89' 'saya' '1.76']


### Import numpy as np

In [60]:
import numpy as np

keluarga = ['kakak', 1.73, 'adik', 1.68, 'ibu', 1.71, 'ayah', 1.89]

keluarga_tambahan = keluarga + ['saya', 1.76]

print(str(len(keluarga_tambahan)) + ' elemen pada keluarga_tambahan')

np_keluarga = np.array(keluarga_tambahan) # Menggunakan NumPy, tapi tidak begitu jelas

print(np_keluarga)

10 elemen pada keluarga_tambahan
['kakak' '1.73' 'adik' '1.68' 'ibu' '1.71' 'ayah' '1.89' 'saya' '1.76']
