# Numpy

## Mengingat list

- <i>powerfull</i>
- Koleksi dari nilai
- Menampung berbagai macam tipe data
- Mengganti, menambah, mengurangi
- Kebutuhan untuk Data Science: Operasi Matematika antar list, <i>speed</i>

In [17]:
tinggi = [1.73, 1.68, 1.71, 1.89, 1.69]

In [18]:
tinggi

[1.73, 1.68, 1.71, 1.89, 1.69]

In [19]:
berat = [65.4, 59.2, 63.6, 88.4, 68.7]

In [7]:
# berat / tinggi ** 2 --> error

## Solusi? Numpy, horray

- Python Numerik
- Alternatif dari list python: NumPy Array
- Kalkulasi semua elemen array
- Mudah dan cepat

In [20]:
import numpy as np
np_tinggi = np.array(tinggi)
np_tinggi

array([1.73, 1.68, 1.71, 1.89, 1.69])

In [21]:
np_berat = np.array(berat)
np_berat

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [22]:
bmi = np_berat / np_tinggi ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 24.05377963])

## Numpy remarks

In [24]:
np.array([1.0, 'is', True]) # Numpy hanya dapat menampung satu tipe

array(['1.0', 'is', 'True'], dtype='<U32')

In [26]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [27]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [28]:
numpy_array + numpy_array

array([2, 4, 6])

## Numpy subsetting

In [30]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 24.05377963])

In [31]:
bmi[1]

20.97505668934241

In [36]:
bmi > 23

array([False, False, False,  True,  True])

In [33]:
bmi[bmi > 23]

array([24.7473475 , 24.05377963])

## 2D Numpy arrays

In [38]:
import numpy as np
np_tinggi = np.array([1.73, 1.68, 1.71, 1.89, 1.69])
np_berat = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

In [39]:
type(np_tinggi)

numpy.ndarray

In [40]:
type(np_berat)

numpy.ndarray

In [52]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.69], [65.4, 59.2, 63.6, 88.4, 68.7]])

In [44]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.69],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [45]:
np_2d.shape

(2, 5)

In [47]:
# np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.69], [ 65.4,  59.2,  63.6,  88.4,  "68.7"]])

In [49]:
np_2d # Ingat hanya bisa satu tipe

array([['1.73', '1.68', '1.71', '1.89', '1.69'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

## Nubsetting Numpy 2D

In [53]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.69])

In [54]:
np_2d[0][2]

1.71

In [55]:
np_2d[0, 2]

1.71

In [56]:
np_2d[:, 1 : 3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [57]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

## NumPy dan Statistika Dasar

In [72]:
tinggi = np.round(np.random.normal(1.75, 0.20, 5000), 2)
berat = np.round(np.random.normal(60.32, 15, 5000), 2)

# np.random.normal(distribution_mean, distribution_standard_deviation, jumlah_sample)

In [73]:
np_city = np.column_stack((tinggi, berat))

In [75]:
np_city

array([[ 1.57, 21.51],
       [ 1.36, 53.03],
       [ 1.79, 49.78],
       ...,
       [ 1.86, 61.39],
       [ 1.59, 36.65],
       [ 1.8 , 52.12]])

In [76]:
np.mean(np_city[:, 0])

1.746072

In [77]:
np.corrcoef(np_city[:, 0], np_city[:, 1])

array([[1.        , 0.00592295],
       [0.00592295, 1.        ]])

In [78]:
np.std(np_city[:, 0])

0.20128380664126957